# Generated by Django 4.2.1 on 2024-02-27 10:20

from django.db import migrations, models
import django_test.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.TextField(default=django_test.models.MLInstanceStatus['active'])),
            ],
        ),
    ]
