# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: django_test/proto/ml_instance.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#django_test/proto/ml_instance.proto\x12\x0bml_instance\".\n\x0fMLInstanceSetup\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"2\n\x12MLInstanceResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"W\n\x06MLData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x16\n\x0c\x66ile_content\x18\n \x01(\x0cH\x00\x12\x18\n\x0e\x62\x61se64_content\x18\x0b \x01(\tH\x00\x42\t\n\x07\x63ontent\"-\n\x08MLImport\x12!\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x13.ml_instance.MLData\"$\n\x10MLImportResponse\x12\x10\n\x08\x66ilename\x18\x01 \x03(\t\"0\n\x10MLInstanceAction\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t2\xad\x04\n\nMLInstance\x12H\n\x05setup\x12\x1c.ml_instance.MLInstanceSetup\x1a\x1f.ml_instance.MLInstanceResponse\"\x00\x12\x45\n\x0bimport_data\x12\x15.ml_instance.MLImport\x1a\x1d.ml_instance.MLImportResponse\"\x00\x12K\n\x07predict\x12\x1d.ml_instance.MLInstanceAction\x1a\x1f.ml_instance.MLInstanceResponse\"\x00\x12J\n\x06\x65xport\x12\x1d.ml_instance.MLInstanceAction\x1a\x1f.ml_instance.MLInstanceResponse\"\x00\x12R\n\x0e\x63reate_dataset\x12\x1d.ml_instance.MLInstanceAction\x1a\x1f.ml_instance.MLInstanceResponse\"\x00\x12H\n\x04logs\x12\x1d.ml_instance.MLInstanceAction\x1a\x1f.ml_instance.MLInstanceResponse\"\x00\x12W\n\x13\x64ownload_checkpoint\x12\x1d.ml_instance.MLInstanceAction\x1a\x1f.ml_instance.MLInstanceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'django_test.proto.ml_instance_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MLINSTANCESETUP']._serialized_start=52
  _globals['_MLINSTANCESETUP']._serialized_end=98
  _globals['_MLINSTANCERESPONSE']._serialized_start=100
  _globals['_MLINSTANCERESPONSE']._serialized_end=150
  _globals['_MLDATA']._serialized_start=152
  _globals['_MLDATA']._serialized_end=239
  _globals['_MLIMPORT']._serialized_start=241
  _globals['_MLIMPORT']._serialized_end=286
  _globals['_MLIMPORTRESPONSE']._serialized_start=288
  _globals['_MLIMPORTRESPONSE']._serialized_end=324
  _globals['_MLINSTANCEACTION']._serialized_start=326
  _globals['_MLINSTANCEACTION']._serialized_end=374
  _globals['_MLINSTANCE']._serialized_start=377
  _globals['_MLINSTANCE']._serialized_end=934
# @@protoc_insertion_point(module_scope)
